version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.12.0
    - 1.9.0
    - 1.9.1
  - dependency-name: regexp_parser
    versions:
    - 2.1.0
  - dependency-name: test-unit
    versions:
    - 3.4.0
  commit-message:
    prefix: chore
