name: macos

on:
  - push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache rubygems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-rubygems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-rubygems-
      - name: Install dependencies
        run: |
          set -eux
          brew install imagemagick
          gem install --no-document \
            bundler \
            -v $(sed -n -e '/^BUNDLED WITH$/, /^   / p' Gemfile.lock | tail -n1)
          bundle config path vendor/bundle
          bundle install --retry 3
      - name: Output versions
        run: |
          set -eux
          ruby --version
          gem --version
          bundle --version
          convert --version
      - name: Run test
        run: |
          set -eux
          bundle exec rake
