name: ubuntu

on:
  push:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        ruby:
          - 2.7
          - 2.6
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build and test with Rake
        run: |
          set -eux
          sudo apt install -y imagemagick
          gem install bundler --no-document
          bundle install --jobs=$(nproc) --retry=3
          bundle exec rake
